// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteConnection(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<models.QueryResult>;

export function GetConnections():Promise<Array<models.Connection>>;

export function GetDatabases(arg1:string):Promise<Array<string>>;

export function GetSchemas(arg1:string):Promise<Array<string>>;

export function GetTableData(arg1:string,arg2:string,arg3:string):Promise<models.QueryResult>;

export function GetTables(arg1:string,arg2:string):Promise<Array<models.Table>>;

export function SaveConnection(arg1:models.Connection):Promise<void>;

export function TestConnection(arg1:models.Connection):Promise<string>;
