// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetDatabases(arg1) {
  return window['go']['main']['App']['GetDatabases'](arg1);
}

export function GetSchemas(arg1) {
  return window['go']['main']['App']['GetSchemas'](arg1);
}

export function GetTableData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
